from pathlib import Path
import re, shutil
from html import escape

root=Path(__file__).parent
out=root/'join-hbx-solar';out.mkdir(exist_ok=True)
source=(root/'index.html').read_text(encoding='utf-8-sig')
header=re.search(r'<header class="hbx-header".*?</header>',source,re.S).group()
header=re.sub(r' (href|src)="(?!https?:|tel:|/|#)([^"]+)"',r' \1="/\2"',header)
header=header.replace(' aria-current="page"','').replace('</div>\n<a class="hbx-header__call"','<a href="/join-hbx-solar/" aria-current="page">Join HBX Solar</a></div>\n<a class="hbx-header__call"')
shutil.copyfile(root/'wp-content/uploads/2026/01/cropped-Kusaaa-solar-logo.png',out/'hbx-solar-logo.png')
header=header.replace('/wp-content/uploads/2026/01/cropped-Kusaaa-solar-logo.png','/join-hbx-solar/hbx-solar-logo.png')
footer=re.search(r'<footer\b.*?</footer>',source,re.S).group()
footer=re.sub(r' (href|src)="(?!https?:|tel:|/|#)([^"]+)"',r' \1="/\2"',footer)
footer=re.sub(r'https?://(?:www\.)?kusaaasolar.com', '',footer,flags=re.I)
footer=re.sub('kusaaa', 'hbx',footer,flags=re.I)
footer=footer.replace('/../','/').replace('/&quot;','').replace('&quot;"','"')
footer=footer.replace('animate-in','').replace('pix-opacity-0','')

def items(xs):return '<ul>'+''.join('<li>'+escape(x)+'</li>' for x in xs)+'</ul>'
def cards(xs):return '<div class="cards">'+''.join(f'<article class="card"><span class="number">{i:02}</span><h3>{a}</h3><p>{b}</p></article>' for i,(a,b) in enumerate(xs,1))+'</div>'
def section(id,kicker,title,body,cls=''):
 return f'<section id="{id}" class="section {cls}"><div class="wrap"><div class="section-head"><span class="eyebrow">{kicker}</span><h2>{title}</h2></div>{body}</div></section>'

parts=['''<main id="main"><section class="hero"><div class="wrap hero-grid"><div><span class="eyebrow">CAREERS • SALES • SOLAR ENERGY</span><h1>Build Your Career<br>with <em>HBX Solar</em></h1><h2>Learn Solar. Build Customers.<br>Grow with HBX Solar.</h2><p>Start your journey in India’s growing solar energy industry with structured training, practical sales experience and a performance-driven career path — all with the flexibility of working from home.</p><div class="actions"><a class="button" href="#application">Apply Now <span>↗</span></a><a class="button secondary" href="#how-it-works">Explore the Program <span>↓</span></a></div><div class="location">Azamgarh District &amp; surrounding areas <span>•</span> Sales &amp; business development</div></div><div class="hero-media"><img src="/wp-content/uploads/2026/04/img-1-1024x683.webp" width="1024" height="683" alt="Solar panels capturing sunlight under a clear sky" fetchpriority="high"><div class="media-label"><span>YOUR NEXT CHAPTER</span><strong>A brighter future.<br>Built by you.</strong><div>LEARN <b>→</b> PERFORM <b>→</b> GROW</div></div><div class="training-tag"><strong>30</strong><span>days of structured<br>solar sales training</span></div></div></div></section><div class="value-strip"><div class="wrap"><span>⌂ &nbsp; Work From Home</span><span>30-Day Training</span><span>Performance Growth</span><span>Solar Industry</span><span>Career Opportunity</span></div></div><nav class="section-nav" aria-label="Explore this page"><div class="wrap"><a href="#overview">The opportunity</a><a href="#how-it-works">Your journey</a><a href="#training">Training</a><a href="#compensation">Growth &amp; compensation</a><a href="#faq">FAQs</a><a href="#application">Apply now ↗</a></div></nav>''']
parts.append(section('overview','A CAREER WITH PURPOSE','Your Career in Solar Starts Here','''<div class="split"><div><p>HBX Solar is building a performance-driven sales and business development network to help more customers adopt solar energy.</p><p>We are looking for motivated individuals who can communicate with customers, generate opportunities, understand customer requirements and help them move toward the right solar solution.</p></div><div><p>You don’t need to be a solar expert on day one. Our structured training program is designed to help you understand solar, develop customer-handling skills and learn the complete sales process.</p><p class="highlight">Experience is valuable.<br>Potential matters too.</p></div></div>'''))
parts.append(section('why-join','THE HBX SOLAR OPPORTUNITY','Why Build Your Career with HBX Solar?',cards([
('Work From Home','Work remotely and connect with customers from your own location.'),('Structured Training','Learn solar products, customer handling, lead generation, sales communication and follow-up.'),('Performance-Based Growth','Your earning potential increases as your customer acquisition performance improves.'),('Real Sales Experience','Work on real customer requirements and understand the complete solar sales journey.'),('Professional Identity','After meeting the required employment criteria, eligible team members receive official HBX Solar credentials and resources.'),('Long-Term Growth','High-performing associates can progress toward senior sales and team leadership responsibilities.')]),'tint'))
parts.append(section('eligibility','POTENTIAL MEETS OPPORTUNITY',"Who We’re Looking For",'<div class="split"><div>'+items(['Candidates from Azamgarh District and surrounding areas','Freshers and experienced sales professionals','People interested in solar energy','Good communication skills and a customer-focused mindset','Willingness to learn'])+'</div><div>'+items(['Ability to work independently','Smartphone and reliable internet connection','Ability to communicate through phone, WhatsApp and digital tools','Comfortable with performance-based targets'])+'</div></div><p class="callout">You don’t need to know everything about solar. You need the willingness to learn and the discipline to perform.</p>'))
journey=[('Apply','Submit your application through the HBX Solar career form.'),('Selection','Shortlisted candidates are contacted and evaluated for the role.'),('30-Day Training','Complete structured training in solar knowledge, customer communication, lead generation and sales.'),('Acquire Your First Customer','Put your training into practice and work toward acquiring your first successful customer.'),('Official HBX Solar Employment','After meeting the defined employment criteria, eligible candidates move into the official employment stage.'),('Grow with Performance','Compensation and career progression can increase based on customer acquisition and company-defined performance slabs.')]
parts.append(section('how-it-works','LEARN → START → ACQUIRE → GROW','Your Journey with HBX Solar','<div class="journey">'+''.join(f'<article><span class="milestone">{i:02}</span><h3>{a}</h3><p>{b}</p></article>' for i,(a,b) in enumerate(journey,1))+'</div>','dark'))
modules=[('Solar Fundamentals',['Solar PV basics','System sizing: 1kW / 2kW / 3kW / 5kW systems','Solar panels and inverters','Mounting structures','Basic electrical concepts','Rooftop solar fundamentals']),('Customer Understanding',['Understanding customer requirements','Electricity consumption','Customer qualification','Identifying suitable solar solutions','Handling customer questions']),('Sales & Communication',['Calling techniques','WhatsApp communication','Lead generation and customer presentation','Objection handling and follow-ups','Negotiation basics','Customer conversion']),('HBX Solar Sales Process',['Lead management and CRM usage','Quotation process','Customer follow-up','Documentation','Internal communication','Reporting and handover process'])]
parts.append(section('training','A STRONG FOUNDATION','30 Days to Build Your Solar Sales Foundation','<p class="lead">Learn the Industry. Learn the Product. Learn the Customer. Learn the Sale.</p><div class="modules">'+''.join(f'<article class="card"><span class="eyebrow">MODULE {i:02}</span><h3>{a}</h3>{items(b)}</article>' for i,(a,b) in enumerate(modules,1))+'</div><p class="note">Training content may be updated according to HBX Solar’s current products, processes and business requirements.</p>'))
parts.append(section('compensation','TRANSPARENT EXPECTATIONS','Performance-Driven Career Structure','''<div class="split compensation"><div><h3>Your growth is connected to your performance.</h3><p>The compensation structure is based on successful customer acquisition and company-defined performance criteria.</p><div class="support"><h4>Performance Support</h4><p>Where applicable, HBX Solar may provide limited performance support during the initial period, subject to company policy, activity requirements and eligibility criteria.</p></div></div><div><table><caption>Monthly compensation by performance stage</caption><thead><tr><th>Performance</th><th>Monthly compensation</th></tr></thead><tbody><tr><td>Initial employment stage</td><td>₹8,000</td></tr><tr><td>5 successful customers</td><td>₹11,000</td></tr><tr><td>6 successful customers</td><td>₹14,000</td></tr><tr><td>7+ customers</td><td>Higher performance opportunity / additional incentive</td></tr></tbody></table></div></div><p class="note">Customer acquisition will be counted only when the customer meets HBX Solar’s defined qualification criteria. The exact definition of a successful customer, payment/booking requirements, applicable incentives and salary terms will be communicated in the official employment documentation.</p><p class="terms">All compensation, employment status, targets and incentives are subject to the official HBX Solar employment terms and applicable company policies.</p>''','tint'))
parts.append(section('first-customer','YOUR FIRST MILESTONE','Your First Customer Can Be Your First Milestone','''<p class="lead">Your first successful customer acquisition is an important milestone in the HBX Solar career journey. Once you meet the company’s defined criteria, you can move into the official employment stage.</p><div class="path"><span>Training<br><strong>Associate</strong></span><span>First successful<br><strong>Customer</strong></span><span>Official HBX Solar<br><strong>Employee</strong></span><span>Career &amp; performance<br><strong>Growth</strong></span></div><h3>After employment confirmation, eligible employees may receive</h3><div class="pills"><span>HBX Solar Official Email ID</span><span>Employee ID Card</span><span>HBX Solar T-Shirt</span><span>Official Sales Resources</span><span>CRM / Reporting Access</span></div><p class="note">Company-provided physical materials will be dispatched to the employee’s registered address where applicable.</p>'''))
parts.append(section('remote','CONNECTED, WHEREVER YOU WORK','Work From Where You Are','''<div class="split"><p class="lead">HBX Solar’s Work From Home sales model allows eligible team members to work remotely while connecting with customers through calls, WhatsApp and digital tools.</p><div class="remote-list">'''+items(['Customer Communication','Digital Sales','Calling & Follow-up','CRM & Reporting','Work From Home'])+'</div></div>','tint'))
parts.append(section('milestones','MAKE YOUR PROGRESS COUNT','Performance Creates Opportunity','<div class="growth-grid">'+''.join(f'<article><strong>{a}</strong><p>{b}</p></article>' for a,b in [('1st Customer','Entry milestone'),('4 Customers','Initial monthly target'),('5 Customers','₹11,000 compensation slab'),('6 Customers','₹14,000 compensation slab'),('20 Customers','Performance milestone / recognition eligibility'),('High Performance','Senior responsibilities / team leadership opportunities')])+'</div><p class="note">Eligibility for higher responsibilities may be based on sustained performance, business requirements and company evaluation.</p>'))
parts.append(section('career','THINK LONG TERM','Where Can This Journey Take You?','<div class="career-path">'+''.join('<span>'+x+'</span>' for x in ['Sales Associate','Senior Sales Associate','Business Development Executive','Team Leader','Sales / Business Development Manager'])+'</div><p class="note">Career progression depends on sustained performance, skills, leadership capability, business requirements and company evaluation.</p>','dark'))
parts.append(section('role','MEANINGFUL WORK. REAL RESPONSIBILITY.','Your Role at HBX Solar','<div class="role-list">'+items(['Generate and develop solar leads','Contact potential customers','Understand customer electricity and solar requirements','Explain suitable solar solutions','Conduct follow-ups','Coordinate with the internal sales/technical team','Maintain customer information in the CRM','Track leads and opportunities','Support customers throughout the sales process','Achieve assigned customer acquisition targets','Maintain professional communication','Submit regular sales/activity reports'])+'</div>'))
parts.append(section('expectations','BRING YOUR COMMITMENT','What We Expect','<div class="split"><article class="card"><h3>We Value</h3><div class="pills">'+''.join('<span>'+x+'</span>' for x in ['Discipline','Communication','Consistency','Customer focus','Learning attitude','Accountability','Professionalism','Integrity'])+'</div></article><article class="card"><h3>We Don’t Expect</h3>'+items(['Years of solar experience','A traditional office setup','Perfect sales skills on day one'])+'</article></div><p class="highlight">We can teach the process. You bring the commitment.</p>','tint'))
parts.append(section('resources','EQUIPPED TO MOVE FORWARD','More Than Just a Sales Role',cards([('Official Company Identity','HBX Solar email ID and employee identity resources after meeting applicable employment criteria.'),('Professional Training','Structured training to develop solar and sales knowledge.'),('Digital Tools','CRM, communication and reporting systems according to role requirements.'),('Company Branding','Eligible employees receive company-branded materials as applicable.'),('Performance Recognition','Recognition opportunities based on achievement and sustained performance.'),('Growth Opportunities','Potential progression into senior sales and leadership roles.')])) )
faq=[('Is this a work-from-home opportunity?','Yes. The program is designed around a Work From Home sales model for eligible candidates.'),('Do I need previous solar experience?','No. Candidates can enter through the structured training program, subject to selection.'),('Is the training paid?','Training payment terms have not yet been published on this page. Please confirm the current policy with HBX Solar’s recruitment team before joining training.'),('When does employment begin?','Official employment begins after you meet the company’s defined employment and confirmation criteria, as set out in the official documentation.'),('What happens after my first customer?','After your first successful customer and completion of the defined criteria, you can move into the official employment stage.'),('How is salary determined?','Compensation is linked to verified customer acquisition and company-defined performance criteria. See the compensation structure above; the official employment terms govern eligibility, targets and payment.'),('Can I work from anywhere?','The primary recruitment focus is Azamgarh District. Candidates from surrounding areas should confirm geographic eligibility with recruitment. Wider eligibility has not been confirmed.'),('What happens if I don’t acquire customers?','The applicable performance review process and any initial support depend on company policy and your official terms. Ask recruitment to explain targets, review periods and the consequences of not meeting them before accepting the opportunity.'),('How are customers counted?','Only acquisitions verified under HBX Solar’s official sales policy count. The precise qualification, booking and payment requirements must be confirmed in the official employment documentation; a lead or enquiry should not be assumed to count.'),('Can I grow into a leadership role?','Yes, subject to sustained performance, capability, business requirements and company evaluation.')]
parts.append(section('faq','A LITTLE MORE CLARITY','Your Questions, Answered','<div class="faqs">'+''.join(f'<details><summary>{a}<span aria-hidden="true">+</span></summary><p>{b}</p></details>' for a,b in faq)+'</div>','tint'))
fields=[('Full Name','text','name'),('Mobile Number','tel','tel'),('WhatsApp Number','tel','tel'),('Email Address','email','email'),('City','text','address-level2'),('District','text','off'),('State','text','address-level1'),('Age','number','off'),('Highest Qualification','text','off'),('Current Occupation','text','organization-title')]
form=''
for label,typ,auto in fields:
 id=label.lower().replace(' ','_'); extra=' min="1" max="120" step="1"' if typ=='number' else (' pattern="[+0-9 ()-]{10,18}" inputmode="tel"' if typ=='tel' else ' maxlength="160"')
 form+=f'<label for="{id}">{label} <span aria-hidden="true">*</span><input id="{id}" name="{id}" type="{typ}" autocomplete="{auto}"{extra} required></label>'
for label,options in [('Sales Experience',['No experience','Less than 1 year','1–3 years','More than 3 years']),('Solar Industry Experience',['No experience','Less than 1 year','1–3 years','More than 3 years']),('Preferred Work Mode',['Work From Home','Other — discuss with recruitment']),('How did you hear about HBX Solar?',['Search engine','Social media','Friend or referral','HBX Solar website','Other'])]:
 id=label.lower().replace(' ','_').replace('?','');form+=f'<label for="{id}">{label} *<select id="{id}" name="{id}" required><option value="">Select an option</option>'+''.join(f'<option>{x}</option>' for x in options)+'</select></label>'
form+='''<label for="languages">Languages Known *<input id="languages" name="languages" placeholder="e.g. Hindi, English" maxlength="160" required></label><label for="resume">Resume Upload <span>(optional)</span><input id="resume" name="resume" type="file" accept=".pdf,.doc,.docx"><small>PDF, DOC or DOCX. Maximum 5 MB. Confirm recruitment’s resume requirements before applying.</small></label><label class="full" for="motivation">Why do you want to join HBX Solar? *<textarea id="motivation" name="motivation" rows="4" maxlength="3000" required></textarea></label><label class="consent full"><input type="checkbox" name="consent" required><span>I confirm that the information provided by me is accurate and I agree to be contacted by HBX Solar regarding this opportunity.</span></label><div class="full"><p id="application-status" role="status" tabindex="-1">Online submission is awaiting activation. You can complete your details, but they cannot be sent yet. Contact HBX Solar to confirm how to apply.</p><button class="button" type="submit">Submit Application <span>↗</span></button><a class="text-link" href="tel:+918608692218">Contact HBX Solar</a></div>'''
parts.append(section('application','TAKE THE FIRST STEP','Ready to Build Your Career with HBX Solar?','<div class="application-intro"><p>Tell us about yourself and the future you want to build.</p><span>* Required fields</span></div><form id="career-form" class="application-form" method="post" enctype="multipart/form-data">'+form+'</form><div class="application-process">'+''.join(f'<div><span class="number">{i:02}</span><h3>{a}</h3><p>{b}</p></div>' for i,(a,b) in enumerate([('Apply','Submit your details.'),('Screening','Our team reviews your application.'),('Interview / Selection','Shortlisted candidates proceed to the next stage.'),('Training','Selected candidates begin the structured training journey.')],1))+'</div>'))
parts.append('''<div class="wrap disclaimer"><p>HBX Solar’s recruitment, training, employment, compensation, customer targets and incentive structures are subject to company policies and official employment documentation. Performance-based compensation is dependent on verified customer acquisition and applicable eligibility criteria. Employment is not guaranteed solely by submitting an application or completing training. Terms may vary based on role, business requirements and applicable policies.</p></div><section class="final-cta"><div class="wrap"><span class="eyebrow">LEARN. PERFORM. GROW.</span><h2>Your Next Career Move<br>Could Start Here.</h2><p>Learn the solar industry. Build your sales skills.<br>Acquire customers. Grow with HBX Solar.</p><div class="actions"><a class="button" href="#application">Apply to Join HBX Solar ↗</a><a class="button secondary" href="tel:+918608692218">Talk to Our Recruitment Team</a></div></div></section></main><a class="mobile-apply button" href="#application">Apply to Join HBX Solar ↗</a>''')
styles=['/wp-content/plugins/elementor/assets/css/frontend.min-1.css','/wp-content/uploads/elementor/css/post-6988-1.css']
html='''<!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Join HBX Solar | Careers &amp; Work From Home Solar Opportunities</title><meta name="description" content="Explore career opportunities with HBX Solar. Join our solar sales and business development program with structured training, work-from-home flexibility and performance-based career growth."><link rel="icon" href="/join-hbx-solar/hbx-solar-logo.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&amp;family=Poppins:wght@400;500;600;700;800&amp;display=swap" rel="stylesheet">'''+''.join(f'<link rel="stylesheet" href="{s}">' for s in styles)+'''<link rel="stylesheet" href="/join-hbx-solar/careers.css"><script src="/join-hbx-solar/config.js" defer></script><script src="/join-hbx-solar/careers.js" defer></script></head><body class="hbx-careers"><a class="skip-link" href="#main">Skip to content</a>'''+header+'<noscript><style>#career-form button[type=submit]{display:none}</style><p class=wrap>JavaScript is required for online applications. Please contact HBX Solar for application assistance.</p></noscript>'+''.join(parts)+footer+'</body></html>'
(out/'index.html').write_text(html,encoding='utf-8')
print('Created join-hbx-solar/index.html')
