"""Compact eight-section careers page content used by build_join_page.py."""
from html import escape

def icon(kind):
    paths = {
        'home':'M3 10 12 3l9 7M5 9v12h14V9M9 21v-8h6v8',
        'training':'m2 8 10-5 10 5-10 5L2 8Zm4 2v7c4 3 8 3 12 0v-7M22 8v8',
        'solar':'M5 10h14l3 10H2l3-10Zm3 0-1 10m9-10 1 10M4 15h16M12 2v3M5 3l2 3m12-3-2 3',
        'growth':'M4 20V4m0 16h17M7 15l5-5 4 2 5-7m-5 0h5v5',
        'career':'M3 7h18v14H3V7Zm5 0V3h8v4M3 12h18M10 12v3h4v-3',
        'people':'M16 21v-3a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v3M9 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8M17 3a4 4 0 0 1 0 8m2 3a4 4 0 0 1 3 4v3',
        'mail':'M3 5h18v14H3V5Zm0 1 9 7 9-7',
        'id':'M3 4h18v16H3V4ZM8 8a2 2 0 1 0 0 4 2 2 0 0 0 0-4M5 17v-1a3 3 0 0 1 6 0v1m3-8h4m-4 4h4',
        'shirt':'m8 3-6 4 3 5 3-2v11h8V10l3 2 3-5-6-4c0 4-8 4-8 0Z',
        'phone':'M6 2h12v20H6V2Zm4 17h4',
    }
    return f'<svg class="line-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="{paths.get(kind,paths["career"])}"/></svg>'

def section(id,eyebrow,title,body,cls=''):
    return f'<section id="{id}" class="section {cls}"><div class="wrap"><div class="section-head"><span class="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{body}</div></section>'

def build():
    p=['''<main id="main"><section class="hero"><div class="wrap hero-grid"><div><span class="eyebrow">CAREERS • SOLAR • WORK FROM HOME</span><h1>Build Your Career<br>with <em>HBX Solar</em></h1><h2>Learn Solar. Build Customers.<br>Grow with HBX Solar.</h2><p>Join our work-from-home solar sales program, receive structured training and build your career through performance-driven growth.</p><div class="actions"><a class="button" href="#application">Apply Now ↗</a><a class="button secondary" href="#how-it-works">How It Works ↓</a></div><div class="location">Azamgarh District &amp; eligible surrounding areas</div></div><div class="hero-media"><img src="/wp-content/uploads/2026/04/img-1-1024x683.webp" width="1024" height="683" alt="Solar panels capturing sunlight under a clear sky" fetchpriority="high"><div class="media-label"><span>YOUR NEXT CHAPTER</span><strong>A brighter future.<br>Built by you.</strong><div>LEARN <b>→</b> PERFORM <b>→</b> GROW</div></div><div class="training-tag"><strong>30</strong><span>days of structured<br>solar sales training</span></div></div></div></section><div class="value-strip"><div class="wrap">'''+''.join(f'<span>{icon(i)}{t}</span>' for i,t in [('home','Work From Home'),('training','30-Day Training'),('solar','Solar Industry'),('growth','Performance Growth'),('career','Career Opportunity')])+'''</div></div>''']
    steps=[('Apply','Submit your application.'),('30-Day Training','Learn solar, customer handling and sales.'),('First Customer','Apply your skills and acquire your first successful customer.'),('Employment Stage','Become eligible for official employment after meeting company criteria.'),('Grow & Earn','Improve performance to qualify for higher compensation and career growth.')]
    p.append(section('how-it-works','FIVE STEPS. ONE CLEAR DIRECTION.','Your Journey with HBX Solar','<ol class="journey">'+''.join(f'<li><article><span class="milestone">{n:02}</span><h3>{a}</h3><p>{b}</p></article></li>' for n,(a,b) in enumerate(steps,1))+'</ol>','dark'))
    modules=[('solar','Solar Basics','Panels, inverters, system sizing and rooftop solar.'),('people','Customer Handling','Understand customer needs and answer questions.'),('phone','Sales Skills','Calling, lead generation, follow-ups and conversion.'),('career','HBX Solar Process','CRM, quotation, reporting and customer coordination.')]
    p.append(section('training','YOUR 30-DAY FOUNDATION',"What You’ll Learn",'<div class="compact-cards">'+''.join(f'<article class="card">{icon(i)}<h3>{a}</h3><p>{b}</p></article>' for i,a,b in modules)+'</div><p class="note">No prior solar expertise is required; selected candidates receive structured training.</p>'))
    slabs=[('Initial Stage','₹8,000','Upon employment eligibility'),('5 Customers','₹11,000','Verified successful customers'),('6 Customers','₹14,000','Verified successful customers'),('Higher Performance','Grow further','Additional growth / incentive opportunities')]
    ladder='<div class="ladder" aria-label="Monthly compensation by performance stage">'+''.join(f'<article class="rung rung-{i}"><span>{a}</span><strong>{b}</strong><small>{c}</small></article>' for i,(a,b,c) in enumerate(slabs,1))+'</div>'
    career='<div class="career-inline"><h3>A path to greater responsibility</h3><div class="career-path">'+''.join('<span>'+x+'</span>' for x in ['Sales Associate','Senior Sales Associate','Team Leader','Sales / Business Development Manager'])+'</div><p class="note">Progression depends on sustained performance, skills, leadership capability, business requirements and company evaluation.</p></div>'
    p.append(section('compensation','PERFORMANCE-BASED MONTHLY COMPENSATION','Your Performance. Your Growth.',ladder+'<div class="target-note"><strong>Month 1 target: 4 successful customers</strong><p>Compensation is subject to verified customer acquisition, eligibility criteria and official HBX Solar employment terms.</p></div>'+career,'tint'))
    path='<ol class="identity-path">'+''.join('<li>'+x+'</li>' for x in ['Training','First Successful Customer','Employment Confirmation','HBX Solar Professional Identity'])+'</ol>'
    resources='<div class="identity-resources">'+''.join(f'<span>{icon(i)}{t}</span>' for i,t in [('mail','Company Email ID'),('id','Employee ID Card'),('shirt','HBX Solar T-Shirt'),('career','Official Sales Resources')])+'</div>'
    p.append(section('identity','A MILESTONE THAT MEANS MORE','From Your First Customer to Your HBX Solar Identity',path+resources+'<p class="note">Provided to eligible employees after meeting the company’s defined employment criteria.</p>'))
    eligibility=['Azamgarh District & eligible surrounding areas','Freshers or experienced candidates','Good communication skills','Smartphone + internet','Willingness to learn','Customer-focused & target-oriented mindset']
    p.append(section('eligibility','BRING YOUR POTENTIAL','Who Can Apply?','<ul class="eligibility-grid">'+''.join('<li>'+x+'</li>' for x in eligibility)+'</ul><p class="eligibility-close">You don’t need to be a solar expert. We train you.</p>','tint'))
    fields=[('Full Name','full_name','text','name'),('Mobile Number','mobile_number','tel','tel'),('WhatsApp Number','whatsapp_number','tel','tel'),('Email','email_address','email','email'),('City','city','text','address-level2'),('District','district','text','off'),('Education','education','text','off'),('Current Occupation','current_occupation','text','organization-title')]
    form=''
    for label,id,typ,auto in fields:
        extra=' pattern="[+0-9 ()-]{10,18}" inputmode="tel"' if typ=='tel' else ' maxlength="160"'
        form+=f'<label for="{id}">{label} *<input id="{id}" name="{id}" type="{typ}" autocomplete="{auto}"{extra} required></label>'
    form+='''<label for="sales_experience">Sales Experience *<select id="sales_experience" name="sales_experience" required><option value="">Select experience</option><option>No experience</option><option>Less than 1 year</option><option>1–3 years</option><option>More than 3 years</option></select></label><label for="resume">Upload Resume <span>(optional)</span><input id="resume" name="resume" type="file" accept=".pdf,.doc,.docx" aria-describedby="resume-help"><small id="resume-help">PDF, DOC or DOCX · Up to 5 MB</small></label><label class="full" for="motivation">Why do you want to join HBX Solar? *<textarea id="motivation" name="motivation" rows="2" maxlength="3000" required></textarea></label><label class="consent full"><input type="checkbox" name="consent" required><span>I confirm my information is accurate and agree to be contacted by HBX Solar about this opportunity.</span></label><div class="full"><p id="application-status" role="status" tabindex="-1">Online applications are awaiting activation. Please contact HBX Solar to confirm how to apply.</p><button class="button" type="submit">Apply Now ↗</button><a class="text-link" href="tel:+918608692218">Contact recruitment</a></div>'''
    p.append(section('application','TAKE THE FIRST STEP','Ready to Join HBX Solar?','<div class="application-intro"><p>Take the First Step Toward Your Solar Career.</p><span>* Required fields</span></div><form id="career-form" class="application-form" method="post" enctype="multipart/form-data">'+form+'</form>'))
    faq=[('Is this a Work From Home opportunity?','Yes. Eligible candidates work remotely using calls and digital tools.'),('Do I need previous solar experience?','No. Freshers and experienced candidates can apply, subject to selection.'),('How does the 30-day training work?','Selected candidates learn solar basics, customer handling, sales and HBX Solar processes. Confirm training payment terms with recruitment before joining.'),('When does official employment begin?','After meeting HBX Solar’s defined criteria and receiving employment confirmation. An application, training or first customer alone does not guarantee employment.'),('How is performance-based compensation calculated?','Monthly slabs depend on verified successful customers and eligibility. Official employment terms define customer qualification, booking/payment requirements and incentives.')]
    p.append(section('faq','GOOD TO KNOW','A Few Quick Answers','<div class="faqs">'+''.join(f'<details><summary>{a}<span aria-hidden="true">+</span></summary><p>{b}</p></details>' for a,b in faq)+'</div>','tint'))
    p.append('</main><a class="mobile-apply button" href="#application">Apply Now ↗</a>')
    return p
