"""Careers page content used by build_join_page.py."""
from html import escape

def icon(kind):
    paths = {
        'home':'M3 10 12 3l9 7M5 9v12h14V9M9 21v-8h6v8',
        'training':'m2 8 10-5 10 5-10 5L2 8Zm4 2v7c4 3 8 3 12 0v-7M22 8v8',
        'solar':'M5 10h14l3 10H2l3-10Zm3 0-1 10m9-10 1 10M4 15h16M12 2v3M5 3l2 3m12-3-2 3',
        'growth':'M4 20V4m0 16h17M7 15l5-5 4 2 5-7m-5 0h5v5',
        'career':'M3 7h18v14H3V7Zm5 0V3h8v4M3 12h18M10 12v3h4v-3',
        'people':'M16 21v-3a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v3M9 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8M17 3a4 4 0 0 1 0 8m2 3a4 4 0 0 1 3 4v3',
        'mail':'M3 5h18v14H3V5Zm0 1 9 7 9-7',
        'id':'M3 4h18v16H3V4ZM8 8a2 2 0 1 0 0 4 2 2 0 0 0 0-4M5 17v-1a3 3 0 0 1 6 0v1m3-8h4m-4 4h4',
        'shirt':'m8 3-6 4 3 5 3-2v11h8V10l3 2 3-5-6-4c0 4-8 4-8 0Z',
        'phone':'M6 2h12v20H6V2Zm4 17h4',
    }
    return f'<svg class="line-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="{paths.get(kind,paths["career"])}"/></svg>'

def section(id,eyebrow,title,body,cls=''):
    return f'<section id="{id}" class="section {cls}"><div class="wrap"><div class="section-head"><span class="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{body}</div></section>'

def build():
    p=['''<main id="main"><section class="hero"><div class="wrap hero-grid"><div><span class="eyebrow">CAREERS • SOLAR • WORK FROM HOME</span><h1><span>₹10,000 Monthly Salary</span> + Performance Bonuses</h1><h2>High Performers Can Earn Up to ₹23,000/Month</h2><p class="hero-promise">Build customers. Grow your performance. Increase your earning potential.</p><p>Start your journey in India's growing solar industry with <strong>HBX Solar</strong>. Work From Home, receive structured training, build real customers and unlock higher monthly earnings through performance.</p><div class="actions"><a class="button" href="#application">Apply Now ↗</a><a class="button secondary" href="#how-it-works">Explore the Opportunity ↓</a></div><p class="hero-policy">Earnings, bonuses and eligibility are subject to HBX Solar's applicable performance and employment policies.</p></div><div class="hero-media"><img src="/wp-content/uploads/2026/04/img-1-1024x683.webp" width="1024" height="683" alt="Solar panels capturing sunlight under a clear sky" fetchpriority="high"><div class="media-label"><span>YOUR NEXT CHAPTER</span><strong>A brighter future.<br>Built by you.</strong><div>LEARN <b>→</b> PERFORM <b>→</b> GROW</div></div><div class="training-tag"><strong>30</strong><span>days of structured<br>solar sales training</span></div></div></div></section><div class="value-strip"><div class="wrap">'''+''.join(f'<article>{icon(i)}<h3>{t}</h3><p>{d}</p></article>' for i,t,d in [('home','Work From Home','Build your career remotely with HBX Solar.'),('training','30-Day Structured Training','Learn solar products, customer handling, sales and HBX Solar processes.'),('solar','Growing Solar Industry','Build your career in India’s rapidly expanding renewable-energy sector.'),('growth','Performance-Based Growth','Higher performance creates higher earning opportunities.'),('career','Career Progression','Grow toward higher sales and leadership responsibilities.')])+'''</div></div>''']
    reasons=[('training','Professional Training','Build practical solar and sales knowledge.'),('home','Work From Home','Develop your career from your own location.'),('growth','Performance-Based Earnings','Verified results can unlock additional bonuses.'),('people','Sales & Business Development Experience','Build real customer relationships and sales skills.'),('career','Recognition & Achievement Rewards','Eligible milestones can earn rewards and recognition.'),('solar','Career Growth Opportunities','Progress toward greater responsibility over time.')]
    p.append(section('why-join','BUILD SKILLS. BUILD A FUTURE.','Why Build Your Career with HBX Solar?','<div class="why-cards">'+''.join(f'<article class="card">{icon(i)}<h3>{t}</h3><p>{d}</p></article>' for i,t,d in reasons)+'</div>'))
    steps=[('Apply','Submit your application.'),('Learn','Complete the structured 30-day training program.'),('Start Selling','Use HBX Solar’s training, tools and sales resources.'),('Build Customers','Generate and manage genuine new customer opportunities.'),('Grow Your Earnings','Performance determines additional earning opportunities.'),('Grow Your Career','Consistent performance can lead to greater responsibility and career progression.')]
    p.append(section('how-it-works','LEARN. PERFORM. PROGRESS.','Your Journey with HBX Solar','<ol class="journey">'+''.join(f'<li><article><span class="milestone">{n:02}</span><h3>{a}</h3><p>{b}</p></article></li>' for n,(a,b) in enumerate(steps,1))+'</ol>','dark'))
    modules=[('solar','Solar Fundamentals','Understand solar systems, products and basic system requirements.'),('people','Customer Handling','Understand customer requirements and communicate professionally.'),('phone','Sales Skills','Develop calling, presentation, objection-handling and closing skills.'),('career','HBX Solar Process','Lead management, follow-ups, quotations, CRM and reporting processes.')]
    p.append(section('training','YOUR 30-DAY FOUNDATION','Start Strong with Structured Training','<p class="training-intro">You don’t need to be a solar expert to start. HBX Solar provides structured training to help you understand the industry, communicate with customers and confidently represent the company.</p><div class="compact-cards">'+''.join(f'<article class="card">{icon(i)}<h3>{a}</h3><p>{b}</p></article>' for i,a,b in modules)+'</div><p class="note">Confirm training payment terms with recruitment before joining.</p>'))
    earning='''<div class="earning-visual"><article><span class="eyebrow">MONTHLY SALARY</span><strong>₹10,000</strong><p>+ Performance Bonuses</p></article><span class="earning-arrow" aria-hidden="true">→</span><article><span class="eyebrow">TOTAL MONTHLY CASH EARNINGS</span><strong><small>Up to</small> ₹23,000<span>/Month</span></strong><p>At the 10 verified NEW customer achievement level</p></article></div><p class="earning-copy">The more verified new customers you successfully acquire, the greater your performance-based earning opportunity.</p><div class="earning-flow"><span>Base Opportunity</span><span>Performance Bonus</span><span>Higher Earnings</span><span>Achievement Recognition</span></div><a class="button secondary earnings-trigger" href="#compensation-details">See How Earnings Work ↓</a><details id="compensation-details" class="compensation-details"><summary>Compensation structure &amp; eligibility<span aria-hidden="true">+</span></summary><div class="cash-breakdown"><span class="eyebrow">10 VERIFIED NEW CUSTOMERS · ONE MONTHLY PERFORMANCE CYCLE</span><h3>₹23,000 Total Monthly Earnings</h3><div class="cash-parts"><div><strong>₹10,000</strong><span>Salary</span></div><b aria-hidden="true">+</b><div><strong>₹12,000</strong><span>Performance Bonus</span></div><b aria-hidden="true">+</b><div><strong>₹1,000</strong><span>Achievement Bonus</span></div></div></div><div class="terms-grid"><div><h3>Salary eligibility: 4 new customers</h3><p>₹10,000 monthly salary requires 4 verified NEW customers in the monthly performance cycle, subject to applicable employment eligibility.</p></div><div><h3>10 new customers: ₹23,000 total cash</h3><p>At 10 verified NEW customers in the same monthly cycle: ₹10,000 salary + ₹12,000 performance bonus + ₹1,000 achievement bonus. This is total monthly cash earnings, not a ₹23,000 salary.</p></div><div><h3>A fresh count every month</h3><p>Customer count resets every month. Only verified NEW customers acquired during that month are counted. Official policy determines customer verification and booking/payment requirements.</p></div><div><h3>Achievement Reward: additional</h3><p>A separate Achievement Reward may be provided additionally when applicable. It is not included in the ₹23,000 total monthly cash earnings.</p></div></div><p class="note">Earnings, bonuses and eligibility are subject to HBX Solar’s applicable performance and employment policies.</p></details>'''
    recognition='<div class="recognition"><h3>Performance That Gets Recognized</h3><p>At HBX Solar, strong performance is not only rewarded through earnings—it is also recognized through achievement-based incentives and rewards.</p><div class="recognition-cards">'+''.join(f'<article>{icon(i)}<h4>{t}</h4><p>{d}</p></article>' for i,t,d in [('growth','Performance Bonus','₹12,000 performance bonus at 10 verified NEW customers in one monthly cycle.'),('career','Achievement Bonus','₹1,000 achievement bonus at the 10 verified NEW customer level.'),('solar','Achievement Rewards','Separate company rewards and recognition may be provided additionally when applicable; not included in ₹23,000.')])+'</div></div>'
    p.append(section('compensation','A CLEAR CONNECTION BETWEEN PERFORMANCE & GROWTH','Your Performance Can Take Your Earnings Higher',earning+recognition,'tint'))
    resources='<div class="identity-resources">'+''.join(f'<span>{icon(i)}{t}</span>' for i,t in [('mail','Official HBX Solar Email ID'),('id','Employee ID'),('shirt','HBX Solar T-Shirt'),('career','Official Sales Resources'),('growth','CRM / Sales Tools'),('training','Professional Training & Support')])+'</div>'
    career='<div class="career-inline"><h3>Your career can grow with you</h3><div class="career-path">'+''.join('<span>'+x+'</span>' for x in ['Business Development & Sales Associate','Senior Sales Associate','Team Leader','Sales / Business Development Manager'])+'</div><p class="note">Consistent performance, skill development and leadership ability can create opportunities for career progression within HBX Solar, subject to company requirements and available roles.</p></div>'
    p.append(section('identity','PROFESSIONAL IDENTITY. SHARED AMBITION.','Become Part of the HBX Solar Team',resources+'<p class="note">Provided to eligible employees after completing applicable onboarding and employment requirements. Applying, training or acquiring a first customer alone does not guarantee employment.</p>'+career))
    eligibility=['Freshers and experienced candidates','Strong communication skills','Comfortable speaking with customers','Smartphone and reliable internet connection','Willingness to learn','Customer-focused mindset','Sales-oriented attitude','Ability to work independently from home']
    p.append(section('eligibility','BRING YOUR POTENTIAL',"Who We’re Looking For",'<ul class="eligibility-grid">'+''.join('<li>'+x+'</li>' for x in eligibility)+'</ul><p class="eligibility-close">Primary recruitment focus: Azamgarh District and eligible surrounding areas.</p>','tint'))
    fields=[('Full Name','full_name','text','name'),('Mobile Number','mobile_number','tel','tel'),('WhatsApp Number','whatsapp_number','tel','tel'),('Email Address','email_address','email','email'),('City','city','text','address-level2'),('District','district','text','off'),('Highest Education','education','text','off'),('Current Occupation','current_occupation','text','organization-title')]
    form=''
    for label,id,typ,auto in fields:
        extra=' pattern="[+0-9 ()-]{10,18}" inputmode="tel"' if typ=='tel' else ' maxlength="160"'
        form+=f'<label for="{id}">{label} *<input id="{id}" name="{id}" type="{typ}" autocomplete="{auto}"{extra} required></label>'
    form+='''<label for="sales_experience">Sales Experience *<select id="sales_experience" name="sales_experience" required><option value="">Select experience</option><option>No experience</option><option>Less than 1 year</option><option>1–3 years</option><option>More than 3 years</option></select></label><div class="resume-note"><strong>Resume (optional)</strong><small>Attach your resume in your email app before sending. Files cannot be attached automatically from this page.</small></div><label class="full" for="motivation">Why do you want to join HBX Solar? *<textarea id="motivation" name="motivation" rows="2" maxlength="3000" required></textarea></label><label class="consent full"><input type="checkbox" name="consent" required><span>I confirm my information is accurate and agree to be contacted by HBX Solar about this opportunity.</span></label><div class="full"><p id="application-status" role="status" tabindex="-1">Submit Application opens your email app with all details filled in for careers@hbxsolar.in. Review the email and click Send to complete your application.</p><button class="button" type="submit">Submit Application ↗</button><p class="recruitment-help">For any doubt call at <a href="tel:+918608692978">+91 86086 92978</a></p><div id="email-draft" hidden><p>No email app opened? Copy your details and email them to <a href="mailto:careers@hbxsolar.in">careers@hbxsolar.in</a>.</p><label for="email-body">Your application email</label><textarea id="email-body" rows="6" readonly></textarea><div class="actions"><a id="open-email" class="button secondary" href="mailto:careers@hbxsolar.in">Open Email Again</a><button id="copy-application" class="button secondary" type="button">Copy Application Details</button></div></div></div>'''
    p.append(section('application','TAKE THE FIRST STEP','Ready to Build Your Career with HBX Solar?','<div class="application-invite"><p>Take the first step toward a career in India’s growing solar industry.</p><a class="button" href="#career-form">Apply Now ↗</a><p class="invite-benefits">Work From Home • Structured Training • ₹10,000 Monthly Salary + Performance Bonuses • Career Growth</p></div><p class="required-note">* Required fields</p><form id="career-form" class="application-form" method="post" enctype="multipart/form-data">'+form+'</form>'))
    faq=[('Is this a Work From Home opportunity?','Yes, the role is designed as a Work From Home sales/business development opportunity, subject to the applicable role requirements.'),('Do I need previous solar experience?','No. HBX Solar provides structured training for eligible candidates.'),('Is there a salary and performance bonus?','Yes. The compensation structure includes a monthly salary component along with performance-based bonuses, subject to applicable eligibility criteria.'),('Can high performers earn more?','Yes. At 10 verified NEW customers in one month, total monthly cash is ₹23,000: ₹10,000 salary + ₹12,000 performance bonus + ₹1,000 achievement bonus. Any applicable Achievement Reward is separate. Customer counts reset monthly.'),('How do I apply?','Complete the form and click Submit Application to open a pre-filled email to careers@hbxsolar.in. Attach your resume if needed, then click Send in your email app. For any doubt call +91 86086 92978.')]
    p.append(section('faq','GOOD TO KNOW','A Few Quick Answers','<div class="faqs">'+''.join(f'<details><summary>{a}<span aria-hidden="true">+</span></summary><p>{b}</p></details>' for a,b in faq)+'</div>','tint'))
    p.append('</main><a class="mobile-apply button" href="#application">Apply Now ↗</a>')
    return p
